services:

  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: magomed
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: phonebook
      PGDATA: /data/postgres
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./postgres:/data/postgres
    ports:
      - "5442:5432"
